apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "quay.io/minio/minio:RELEASE.2022-03-17T06-34-49Z"
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "500Mi"
              cpu: "500m"
              ephemeral-storage: "500Mi"
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: console
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: secret-key
          volumeMounts:
            - name: minio
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: minio
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: minio
      port: 9000
      targetPort: minio
      protocol: TCP
    - name: console
      port: 9001
      targetPort: console
      protocol: TCP