name: Build and Push Backend

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build and Test with Maven
        run: |
          cd backend/server/
          mvn -B clean package -Pnative --file pom.xml
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: ./backend/server/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: keyruu
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: backend/server/
          file: backend/server/src/main/docker/Dockerfile.native-micro
          push: true
          tags: ghcr.io/keyruu/nexcalimat/server:latest
