name: Build and Push Frontend

on:
  push:
    paths:
      - frontend/**
    branches:
      - main

jobs:
  frontend:
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          context: frontend/
          cmd: install
      - name: Build with yarn
        uses: borales/actions-yarn@v4
        with:
          context: frontend/
          cmd: build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: keyruu
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: frontend/
          file: frontend/docker/image/Dockerfile
          push: true
          tags: ghcr.io/keyruu/nexcalimat/frontend:latest
